[2025-04-30T20:19:33.957+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.extract_and_upload_files manual__2025-04-30T20:11:46.623005+00:00 [queued]>
[2025-04-30T20:19:33.973+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.extract_and_upload_files manual__2025-04-30T20:11:46.623005+00:00 [queued]>
[2025-04-30T20:19:33.975+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-04-30T20:19:34.005+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_upload_files> on 2025-04-30 20:11:46.623005+00:00
[2025-04-30T20:19:34.010+0000] {standard_task_runner.py:60} INFO - Started process 5574 to run task
[2025-04-30T20:19:34.014+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'extract_and_upload_files', 'manual__2025-04-30T20:11:46.623005+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmprahys4l8']
[2025-04-30T20:19:34.016+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask extract_and_upload_files
[2025-04-30T20:19:34.283+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.extract_and_upload_files manual__2025-04-30T20:11:46.623005+00:00 [running]> on host e4f2445a264f
[2025-04-30T20:19:34.686+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_upload_files' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T20:11:46.623005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T20:11:46.623005+00:00'
[2025-04-30T20:19:34.734+0000] {base.py:83} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2025-04-30T20:19:34.736+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2025-04-30T20:19:35.266+0000] {etl_pipeline.py:275} ERROR - Failed to extract and upload files: 'utf-8' codec can't decode byte 0xc9 in position 22: invalid continuation byte
[2025-04-30T20:19:35.267+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 252, in extract_and_upload_files
    zip_data = s3_hook.read_key(key=zip_key, bucket_name=MINIO_BUCKET_RAW)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 137, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 971, in read_key
    return obj.get()["Body"].read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 22: invalid continuation byte
[2025-04-30T20:19:35.305+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=extract_and_upload_files, execution_date=20250430T201146, start_date=20250430T201933, end_date=20250430T201935
[2025-04-30T20:19:35.336+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task extract_and_upload_files ('utf-8' codec can't decode byte 0xc9 in position 22: invalid continuation byte; 5574)
[2025-04-30T20:19:35.350+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T20:19:35.408+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
