[2025-05-01T00:50:21.283+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:50:21.294+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:50:21.295+0000] {taskinstance.py:2193} INFO - Starting attempt 39 of 40
[2025-05-01T00:50:21.314+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_cleaned_data_to_minio> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:50:21.319+0000] {standard_task_runner.py:60} INFO - Started process 21943 to run task
[2025-05-01T00:50:21.323+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_cleaned_data_to_minio', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp88ayx71m']
[2025-05-01T00:50:21.326+0000] {standard_task_runner.py:88} INFO - Job 202: Subtask load_cleaned_data_to_minio
[2025-05-01T00:50:21.557+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:50:21.831+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_cleaned_data_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='39' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:50:21.848+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 175, in load_cleaned_data_to_minio
    df = pd.read_parquet(output_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/01-05-2025_capitalbikeshare-tripdata.parquet'
[2025-05-01T00:50:21.877+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=load_cleaned_data_to_minio, execution_date=20250430T230413, start_date=20250501T005021, end_date=20250501T005021
[2025-05-01T00:50:21.902+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task load_cleaned_data_to_minio ([Errno 2] No such file or directory: '/opt/airflow/dags/data/01-05-2025_capitalbikeshare-tripdata.parquet'; 21943)
[2025-05-01T00:50:21.943+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:50:22.011+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
